#pragma once

#define FP_NAN 0
#define FP_INFINITE 1
#define FP_ZERO 2
#define FP_SUBNORMAL 3
#define FP_NORMAL 4

extern "C" {
float tanhf(float);
int ilogb(double);
float tgammaf(float);
float fabsf(float);
long long llrint(double);
long double rintl(long double);
long double fmaxl(long double, long double);
float nextafterf(float, float);
long double coshl(long double);
double cos(double);
double atanh(double);
long long llrintf(float);
long double cosl(long double);
float sinhf(float);
double scalbln(double, long);
float hypotf(float, float);
long double asinhl(long double);
int ilogbf(float);
long double lgammal(long double);
long lrintf(float);
long double copysignl(long double, long double);
long double sqrtl(long double);
double logb(double);
double remquo(double, double, int*);
long double acoshl(long double);
long double hypotl(long double, long double);
float roundf(float);
double ceil(double);
double copysign(double, double);
double hypot(double, double);
long double powl(long double, long double);
long double frexpl(long double, int*);
double remainder(double, double);
float fmodf(float, float);
long double nearbyintl(long double);
long double fabsl(long double);
float atanf(float);
float rintf(float);
long double truncl(long double);
double fabs(double);
long double sinhl(long double);
long double logl(long double);
double nextafter(double, double);
double exp2(double);
float log2f(float);
double log(double);
long double ldexpl(long double, int);
long double erfcl(long double);
long double nexttowardl(long double, long double);
float atan2f(float, float);
double cosh(double);
double atan2(double, double);
long double sinl(long double);
float log10f(float);
double log1p(double);
float copysignf(float, float);
float logbf(float);
long double nextafterl(long double, long double);
double pow(double, double);
float asinf(float);
long double fminl(long double, long double);
float scalblnf(float, long);
double log2(double);
double fmax(double, double);
long double remainderl(long double, long double);
float fdimf(float, float);
float lgammaf(float);
float exp2f(float);
float ceilf(float);
long double log1pl(long double);
double atan(double);
long double fmodl(long double, long double);
float expf(float);
double frexp(double, int*);
float erff(float);
double sin(double);
long double erfl(long double);
float fmaf(float, float, float);
long double log2l(long double);
double asin(double);
double fma(double, double, double);
long double nanl(const char*);
double sqrt(double);
float coshf(float);
long double scalbnl(long double, int);
double asinh(double);
double sinh(double);
long double roundl(long double);
long double fdiml(long double, long double);
long long llround(double);
float asinhf(float);
float atanhf(float);
int ilogbl(long double);
double expm1(double);
float sqrtf(float);
long double atan2l(long double, long double);
float log1pf(float);
long double tanhl(long double);
long double modfl(long double, long double*);
long double atanl(long double);
float erfcf(float);
long long llroundf(float);
double nearbyint(double);
float logf(float);
long double remquol(long double, long double, int*);
double scalbn(double, int);
long double tgammal(long double);
float remainderf(float, float);
double fmod(double, double);
double tgamma(double);
float acoshf(float);
long double acosl(long double);
double nexttoward(double, long double);
long double fmal(long double, long double, long double);
float tanf(float);
float modff(float, float*);
double lgamma(double);
float nexttowardf(float, long double);
float floorf(float);
long double asinl(long double);
long double scalblnl(long double, long);
float expm1f(float);
float fmaxf(float, float);
double trunc(double);
long double tanl(long double);
double cbrt(double);
double tanh(double);
long long llroundl(long double);
double fmin(double, double);
double erfc(double);
float ldexpf(float, int);
double nan(const char*);
long lrintl(long double);
long lround(double);
long double exp2l(long double);
long lroundf(float);
double acos(double);
long double floorl(long double);
float nearbyintf(float);
float fminf(float, float);
long double log10l(long double);
float nanf(const char*);
long lroundl(long double);
double round(double);
double fdim(double, double);
double acosh(double);
long lrint(double);
float truncf(float);
float acosf(float);
long double ceill(long double);
float cosf(float);
double tan(double);
float remquof(float, float, int*);
float cbrtf(float);
long double expl(long double);
long double logbl(long double);
float powf(float, float);
double floor(double);
float scalbnf(float, int);
long long llrintl(long double);
long double expm1l(long double);
float frexpf(float, int*);
long double atanhl(long double);
double log10(double);
long double cbrtl(long double);
double exp(double);
float sinf(float);
double ldexp(double, int);
double rint(double);
double modf(double, double*);
double erf(double);
int isfinite(double);
int isinf(double);
int isnan(double);
int isnormal(double);
int signbit(double);
int fpclassify(double);
int isfinitef(float);
int isinff(float);
int isnanf(float);
typedef float float_t;
typedef double double_t;
}
